document.getElementById('site-footer').innerHTML = [
  '<div class="footer-grid">',
  '<div><p class="footer-col-title">Shop</p>',
  '<a href="index.html?dept=5" class="footer-link">Men\'s gear</a>',
  '<a href="index.html?dept=5" class="footer-link">Women\'s gear</a>',
  '<a href="index.html?dept=5" class="footer-link">Kids\' gear</a>',
  '<a href="index.html?dept=2" class="footer-link">Equipment</a>',
  '<a href="sale.html" class="footer-link">Sale</a></div>',
  '<div><p class="footer-col-title">Support</p>',
  '<a href="order-status.html" class="footer-link">Order status</a>',
  '<a href="#" class="footer-link">Returns &amp; exchanges</a>',
  '<a href="#" class="footer-link">Sizing guide</a>',
  '<a href="#" class="footer-link">Contact us</a>',
  '<a href="#" class="footer-link">FAQ</a></div>',
  '<div><p class="footer-col-title">Company</p>',
  '<a href="about.html" class="footer-link">About</a>',
  '<a href="https://mtec.edu/programs/software-quality-assurance/" class="footer-link" target="_blank" rel="noopener">Careers</a>',
  '<a href="rewards.html" class="footer-link">Rewards</a>',
  '<a href="gift-cards.html" class="footer-link">Gift cards</a>',
  '<a href="press.html" class="footer-link">Press</a></div>',
  '<div><p class="footer-col-title">Stay connected</p>',
  '<a href="instagram.html" class="footer-link">Instagram</a>',
  '<a href="twitter.html" class="footer-link">X / Twitter</a>',
  '<a href="https://www.youtube.com/watch?v=Aq5WXmQQooo" class="footer-link" target="_blank" rel="noopener">YouTube</a>',
  '<a href="newsletter.html" class="footer-link">Newsletter</a></div>',
  '</div>',
  '<div class="footer-bottom">',
  '<p class="footer-copy">Copyright &copy; 2026 Sports Equip Inc.</p>',
  '<div class="footer-legal"><span>Privacy policy</span><span>Terms of use</span><span>Accessibility</span></div>',
  '</div>'
].join('');
